version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo

  backend:
    build: backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
